// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/accounts/transfer": {
            "post": {
                "description": "Moves money between two accounts atomically. Retrying with the same idempotency_key returns the original transaction instead of transferring again.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Transfer funds",
                "parameters": [
                    {
                        "description": "Transfer details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transactions.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Duplicate request; original transaction returned",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/transactions.Transaction"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "201": {
                        "description": "Transfer settled",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/transactions.Transaction"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request or insufficient funds",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "409": {
                        "description": "Idempotency key reused with different parameters",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded; see Retry-After header",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/accounts/{id}/profile": {
            "get": {
                "description": "Returns a customer's profile. PAN and Aadhaar are masked by the API.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Get account profile",
                "parameters": [
                    {
                        "type": "string",
                        "example": "customer-001",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/accounts.Profile"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded; see Retry-After header",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/loans/evaluate": {
            "post": {
                "description": "Applies deterministic lending rules (no LLM). Rules, first failure wins: credit score \u003e= 650 (LOW_CREDIT_SCORE); 2FA verified (IDENTITY_NOT_VERIFIED); amount \u003c= min(balance x multiplier, ₹1 crore) where the multiplier is 10x for score 750+, 5x for 700-749, 2x for 650-699 (AMOUNT_EXCEEDS_LIMIT).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Evaluate loan eligibility",
                "parameters": [
                    {
                        "description": "Loan request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/loans.EvaluateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Evaluated (approved or rejected)",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/loans.EvaluateResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded; see Retry-After header",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Reports service health. Returns 503 if Postgres is down. Redis being down is reported but still returns 200, because rate limiting fails open.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/health.Status"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/health.Status"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "accounts.Profile": {
            "type": "object",
            "properties": {
                "aadhaar": {
                    "type": "string",
                    "example": "XXXX XXXX 9012"
                },
                "balance": {
                    "type": "number",
                    "example": 125000.5
                },
                "credit_score": {
                    "type": "integer",
                    "example": 742
                },
                "customer_id": {
                    "type": "string",
                    "example": "customer-001"
                },
                "full_name": {
                    "type": "string",
                    "example": "Rahul Sharma"
                },
                "is_2fa_verified": {
                    "type": "boolean",
                    "example": true
                },
                "pan": {
                    "type": "string",
                    "example": "XXXXX1234X"
                }
            }
        },
        "health.Status": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string",
                    "example": "up"
                },
                "redis": {
                    "description": "Redis only backs rate limiting, which fails open, so \"down\" here\ndegrades the service but does not make it unhealthy.",
                    "type": "string",
                    "example": "up"
                }
            }
        },
        "loans.EvaluateRequest": {
            "type": "object",
            "required": [
                "customer_id",
                "loan_amount"
            ],
            "properties": {
                "customer_id": {
                    "type": "string",
                    "maxLength": 64,
                    "example": "customer-001"
                },
                "loan_amount": {
                    "type": "number",
                    "example": 500000
                }
            }
        },
        "loans.EvaluateResult": {
            "type": "object",
            "properties": {
                "approved": {
                    "type": "boolean",
                    "example": true
                },
                "credit_score": {
                    "type": "integer",
                    "example": 742
                },
                "customer_id": {
                    "type": "string",
                    "example": "customer-001"
                },
                "max_eligible_amount": {
                    "type": "number",
                    "example": 540727.75
                },
                "reason": {
                    "type": "string",
                    "enum": [
                        "ELIGIBLE",
                        "LOW_CREDIT_SCORE",
                        "IDENTITY_NOT_VERIFIED",
                        "AMOUNT_EXCEEDS_LIMIT"
                    ],
                    "example": "ELIGIBLE"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Request successful"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "transactions.Transaction": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 5000
                },
                "status": {
                    "type": "string",
                    "example": "SETTLED"
                },
                "transaction_id": {
                    "type": "string",
                    "example": "3f1c2a9e-8b7d-4c6e-9f10-2a3b4c5d6e7f"
                }
            }
        },
        "transactions.TransferRequest": {
            "type": "object",
            "required": [
                "amount",
                "from_account",
                "idempotency_key",
                "to_account"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 5000
                },
                "from_account": {
                    "type": "string",
                    "maxLength": 64,
                    "example": "customer-001"
                },
                "idempotency_key": {
                    "type": "string",
                    "maxLength": 128,
                    "example": "tx-123"
                },
                "to_account": {
                    "type": "string",
                    "maxLength": 64,
                    "example": "customer-002"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Banking Service API",
	Description:      "Core banking API for the bank agent platform. PII is masked at this layer.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
